#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
#include "includes/stub/stub.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

void basic_test(bool debug=false);

int main()
{
  cout << "\n" << endl;

  const bool debug = false;
  
  basic_test(debug);

  cout << "\n\n=====================" << endl;
  return 0;
}


void basic_test(bool debug)
{
  if (stub()) {
    cout << "Passed!" << endl;
  } else {
    cout << "Failed!" << endl;
  }
}
